// components/ui/button.tsx
import * as React from "react";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "@/lib/utils";

const buttonVariants = cva(
  "inline-flex items-center justify-center whitespace-nowrap font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-400 disabled:pointer-events-none disabled:opacity-50",
  {
    variants: {
      size: {
        default: "h-9 px-4 py-2",
        sm: "h-8 px-3 text-sm",
        lg: "h-10 px-8",
        icon: "h-9 w-9",
      },
    },
    defaultVariants: {
      size: "default",
    },
  },
);

interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, size, ...props }, ref) => {
    return (
      <button
        className={cn(buttonVariants({ size, className }))}
        ref={ref}
        {...props}
      />
    );
  },
);
Button.displayName = "Button";

export { Button, buttonVariants };

// src/components/ui/Button.svelte
<script lang="ts">
  import { tv, type VariantProps } from "tailwind-variants";
  import type {
    HTMLAnchorAttributes,
    HTMLButtonAttributes,
  } from "svelte/elements";

  const button = tv({
    base: "font-medium rounded-full leading-none transition-all inline-flex items-center flex-none justify-center gap-2",
    variants: {
      variant: {
        primary:
          "bg-primary text-primary-foreground hover:bg-primary/80 disabled:bg-primary/60",
        secondary: "border bg-secondary border-b-[#0000001A]",
        highlight: "bg-highlight",
        navigation:
          "hover:bg-highlight aria-expanded:bg-highlight focus-visible:ring-2 focus-visible:ring-current focus-visible:ring-offset-2",
      },
      size: {
        default: "px-3 h-9 sm:h-8 text-sm",
        lg: "text-lg px-5 h-12",
        icon: "size-8",
        navigation:
          "h-8 rounded-md px-[9px] gap-2.5 text-[15px] leading-[22px] tracking-[-0.1px]",
      },
    },
    defaultVariants: {
      variant: "primary",
      size: "default",
    },
  });

  type Props = {
    href?: string;
    as?: string;
  } & VariantProps<typeof button> &
    HTMLButtonAttributes;

  let { as, size, variant, ...props }: Props = $props();
  let tag = $derived.by(() => {
    if (props.href) {
      return "a";
    }
    if (as) {
      return as;
    }

    return "button";
  });
</script>

<svelte:element
  this={tag}
  {...props}
  class={button({ size, variant, className: props.class })}
>
  <slot />
</svelte:element>
